# person-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  namespace: exe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: person-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/exe
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: exe
spec:
  type: NodePort
  selector:
    app: person-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
